import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://stage_aithinkitive.uat.provider.ecarehealth.com/auth/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('RubyVOlague@jourrapide.com');
  await page.getByRole('textbox', { name: '*********' }).click();
  await page.getByRole('textbox', { name: '*********' }).fill('Pass@123');
  await page.getByRole('button', { name: 'Let\'s get Started' }).click();
  await page.getByRole('tab', { name: 'Settings' }).click();
  await page.getByText('User Settings').click();
  await page.getByRole('tab', { name: 'Providers' }).click();
  await page.getByRole('button', { name: 'Add Provider User' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('Test');
  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('User');
  await page.getByRole('combobox', { name: 'Provider Type' }).click();
  await page.getByRole('option', { name: 'MD' }).click();
  await page.getByRole('combobox', { name: 'specialities' }).click();
  await page.getByRole('option', { name: 'Behavioral Health & Psychiatry' }).getByRole('checkbox').check();
  await page.getByRole('combobox', { name: 'Role *' }).click();
  await page.getByRole('option', { name: 'Provider' }).click();
  await page.getByRole('combobox', { name: 'Gender *' }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByRole('textbox', { name: 'NPI Number', exact: true }).click();
  await page.getByRole('textbox', { name: 'NPI Number', exact: true }).press('Home');
  await page.getByRole('textbox', { name: 'NPI Number', exact: true }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'NPI Number', exact: true }).press('NumLock');
  await page.getByRole('textbox', { name: 'NPI Number', exact: true }).fill('7858574889');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('testing@yopmail.com');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('.MuiButtonBase-root.MuiButton-root.MuiButton-text').first().click();
  await page.getByTestId('CloseIcon').click();
  await page.getByRole('tab', { name: 'Scheduling' }).click();
  await page.getByText('Availability').click();
  await page.getByRole('combobox', { name: 'Select Provider' }).click();
  await page.getByRole('combobox', { name: 'Select Provider' }).fill('test user');
  await page.getByRole('combobox', { name: 'Select Provider' }).press('Enter');
 
  await page.getByRole('option', { name: 'test user', exact: true }).click();
  await page.getByRole('combobox', { name: 'Visit Mode' }).click();
  await page.getByRole('option', { name: 'Telehealth' }).click();
  await page.getByRole('button', { name: 'Edit Availability' }).click();
  await page.getByRole('combobox', { name: 'Select Provider *' }).click();
  await page.getByRole('combobox', { name: 'Select Provider *' }).fill('test');
  await page.getByRole('option', { name: 'Test User' }).click();
  await page.getByRole('combobox', { name: 'Time Zone *' }).click();
  await page.getByRole('option', { name: 'Pacific Daylight Time (UTC -7)' }).click();
  await page.getByRole('combobox', { name: 'Booking Window *' }).click();
  await page.getByRole('option', { name: '6 Week', exact: true }).click();
  await page.getByRole('tab', { name: 'Thursday' }).click();
  await page.getByRole('combobox', { name: 'Start Time *' }).click();
  await page.getByRole('option', { name: '12:00 AM' }).click();
  await page.getByRole('combobox', { name: 'End Time *' }).click();
  await page.getByRole('option', { name: ':45 PM (23 hrs 45 mins)' }).click();
  await page.getByRole('checkbox', { name: 'Telehealth' }).check();
  await page.getByRole('combobox', { name: 'Duration' }).click();
  await page.getByRole('option', { name: '30 minutes' }).click();
  await page.getByRole('combobox', { name: 'Schedule Notice' }).click();
  await page.getByRole('combobox', { name: 'Schedule Notice' }).click();
  await page.locator('div').filter({ hasText: /^Appointment TypeAppointment TypeDurationDurationSchedule NoticeSchedule Notice$/ }).first().click();
  await page.getByRole('button', { name: 'Save' }).click();
});